In [57]:
import pandas as pd 
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt
from  sklearn.model_selection import train_test_split , GridSearchCV ,GroupKFold
from sklearn.metrics import accuracy_score ,  confusion_matrix ,  precision_score , roc_auc_score , roc_curve
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from pandas_profiling import ProfileReport
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
import pickle

def print_score(clf, X_train, y_train, X_test, y_test, train=True):
    if train:
        pred = clf.predict(X_train)
        clf_report = pd.DataFrame(classification_report(y_train, pred, output_dict=True))
        print("Train Result:\n================================================")
        print(f"Accuracy Score: {accuracy_score(y_train, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{clf_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_train, pred)}\n")
        
    elif train==False:
        pred = clf.predict(X_test)
        clf_report = pd.DataFrame(classification_report(y_test, pred, output_dict=True))
        print("Test Result:\n================================================")        
        print(f"Accuracy Score: {accuracy_score(y_test, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{clf_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_test, pred)}\n")

In [3]:
df = pd.read_csv("winequality-red.csv")
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  ...  density    pH  sulphates  alcohol  quality
0            7.4              0.70         0.00             1.9      0.076  ...   0.9978  3.51       0.56      9.4        5
1            7.8              0.88         0.00             2.6      0.098  ...   0.9968  3.20       0.68      9.8        5
2            7.8              0.76         0.04             2.3      0.092  ...   0.9970  3.26       0.65      9.8        5
3           11.2              0.28         0.56             1.9      0.075  ...   0.9980  3.16       0.58      9.8        6
4            7.4              0.70         0.00             1.9      0.076  ...   0.9978  3.51       0.56      9.4        5

[5 rows x 12 columns]

In [4]:
x = df.drop(columns=['quality'])
y = df.quality

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x, y , test_size=0.2 , random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_train.shape)

(1279, 11)
(320, 11)
(1279,)
(1279,)


In [9]:
knn1 = KNeighborsClassifier()
knn1.fit(x_train, y_train)


KNeighborsClassifier()

In [12]:
pickle.dump(knn1 , open("knn1.pkl", 'wb'))

In [14]:
knn1.score(x_test , y_test)

0.45625

In [15]:
knn1.score(x_train, y_train)

0.6692728694292416

In [16]:
pram  = {
    'n_neighbors':[3,5,7,9],
    'algorithm' : ['auto', 'ball_tree'],
    'leaf_size' : [10 , 15 , 20  ],
    'p' : [1,2],
    'weights' : ['uniform', 'distance']
}

In [18]:
gridCV = GridSearchCV(estimator = knn1 , param_grid= pram)
gridCV.fit(x_train, y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree'],
                         'leaf_size': [10, 15, 20], 'n_neighbors': [3, 5, 7, 9],
                         'p': [1, 2], 'weights': ['uniform', 'distance']})

In [23]:
gridCV.best_estimator_   ### TO SEE THE MODEL 

KNeighborsClassifier(leaf_size=10, n_neighbors=7, p=1, weights='distance')

In [24]:
gridCV.best_params_ ## TO SEE THE PARAMETERS 

{'algorithm': 'auto',
 'leaf_size': 10,
 'n_neighbors': 7,
 'p': 1,
 'weights': 'distance'}

In [28]:
knn2 = KNeighborsClassifier(leaf_size=10, n_neighbors=7, p=1, weights='distance')
knn2.fit(x_train , y_train)
knn2.score(x_test , y_test)

0.621875

In [35]:
print("TEST SCORE : -" ,knn2.score(x_test , y_test)*100)
print("TRAIN SCORE : -" ,knn2.score(x_train , y_train)*100)

TEST SCORE : - 62.18749999999999
TRAIN SCORE : - 100.0


In [36]:
knn3 = KNeighborsClassifier(n_neighbors=21,p= 1 ,weights='distance' , leaf_size=10 , algorithm='auto')
knn3.fit(x_train,y_train)

KNeighborsClassifier(leaf_size=10, n_neighbors=21, p=1, weights='distance')

In [38]:
print("TEST SCORE : -" ,knn3.score(x_test , y_test)*100)
print("TRAIN SCORE : -" ,knn3.score(x_train , y_train)*100)

TEST SCORE : - 60.9375
TRAIN SCORE : - 100.0


In [39]:
import pickle
pickle.dump(knn3, open("knn3.pkl" , "wb"))

In [40]:
pwd

'E:\\Jupyter_Project\\jupyter_projects\\INEURON\\DecisionTree'

In [41]:
ls

 Volume in drive E is Local Disk
 Volume Serial Number is 5439-F112

 Directory of E:\Jupyter_Project\jupyter_projects\INEURON\DecisionTree

31-08-2022  22:13    <DIR>          .
31-08-2022  22:13    <DIR>          ..
31-08-2022  21:39    <DIR>          .ipynb_checkpoints
31-08-2022  00:13         1,071,422 BAGGING TECHNIQUES.ipynb
30-08-2022  22:21        11,782,804 Decision_tree.ipynb
29-08-2022  22:47           212,227 dt_model_1.png
31-08-2022  21:53           142,444 knn1.pkl
31-08-2022  22:13           155,763 knn3.pkl
31-08-2022  22:13            33,337 Untitled.ipynb
21-09-2019  19:06           100,951 winequality-red.csv
               7 File(s)     13,498,948 bytes
               3 Dir(s)  442,893,778,944 bytes free


In [42]:
knn3.predict([x_test.iloc[0]])

C:\Users\hp\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([5], dtype=int64)

In [44]:
knn3.predict(x_test)    ### PREDICTED VALUE 

array([5, 5, 6, 6, 6, 5, 5, 5, 5, 6, 7, 5, 6, 6, 6, 6, 5, 6, 7, 5, 5, 6,
       6, 7, 5, 6, 5, 5, 5, 6, 5, 5, 6, 6, 6, 5, 6, 6, 6, 6, 6, 5, 6, 5,
       6, 6, 6, 6, 5, 6, 5, 5, 5, 5, 5, 6, 6, 5, 6, 5, 5, 6, 5, 5, 6, 6,
       6, 5, 6, 6, 6, 5, 6, 6, 6, 5, 5, 5, 5, 5, 5, 7, 5, 6, 6, 6, 5, 6,
       6, 5, 5, 5, 5, 5, 5, 6, 5, 6, 5, 6, 5, 5, 6, 7, 6, 7, 5, 5, 5, 5,
       6, 5, 6, 5, 6, 5, 5, 6, 5, 6, 6, 6, 6, 5, 5, 5, 6, 5, 5, 6, 6, 5,
       5, 7, 6, 5, 6, 5, 5, 6, 7, 5, 6, 6, 5, 5, 6, 6, 6, 5, 6, 6, 5, 5,
       6, 5, 5, 6, 6, 6, 7, 5, 5, 5, 6, 6, 6, 6, 5, 5, 5, 5, 6, 6, 5, 5,
       6, 5, 5, 5, 5, 6, 5, 6, 5, 6, 5, 5, 7, 6, 6, 6, 6, 6, 5, 5, 5, 6,
       5, 7, 5, 5, 5, 5, 6, 5, 5, 6, 6, 6, 5, 5, 5, 5, 6, 6, 6, 6, 6, 5,
       6, 6, 5, 6, 6, 6, 6, 6, 5, 6, 5, 6, 7, 6, 5, 7, 5, 6, 6, 5, 6, 5,
       5, 7, 6, 7, 5, 5, 7, 5, 6, 5, 5, 5, 6, 5, 6, 6, 5, 6, 5, 6, 5, 7,
       6, 7, 5, 5, 6, 6, 5, 6, 6, 6, 5, 6, 6, 5, 5, 6, 7, 5, 5, 5, 5, 7,
       5, 5, 6, 6, 5, 6, 5, 5, 5, 6, 5, 6, 6, 6, 5,

In [46]:
np.array(y_test)   ###  ACTUAL VALUE

array([6, 5, 6, 5, 6, 5, 5, 5, 5, 6, 7, 3, 5, 5, 6, 7, 5, 7, 8, 5, 5, 6,
       5, 6, 6, 6, 7, 6, 5, 6, 5, 5, 6, 5, 6, 5, 7, 5, 4, 6, 5, 5, 7, 5,
       5, 6, 7, 6, 5, 6, 5, 5, 5, 7, 6, 6, 6, 5, 5, 5, 5, 7, 5, 6, 6, 5,
       6, 5, 6, 5, 6, 4, 6, 6, 6, 5, 8, 5, 6, 6, 5, 6, 5, 6, 6, 7, 5, 6,
       7, 4, 7, 6, 5, 5, 5, 6, 5, 6, 5, 6, 5, 5, 5, 7, 6, 7, 6, 5, 6, 5,
       8, 5, 6, 5, 6, 7, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 7, 6, 5, 5, 6, 5,
       5, 5, 6, 5, 5, 5, 5, 6, 7, 6, 8, 5, 5, 5, 6, 6, 6, 5, 6, 7, 6, 5,
       6, 5, 5, 6, 6, 6, 7, 5, 7, 5, 5, 5, 6, 6, 5, 5, 6, 5, 7, 6, 7, 6,
       6, 5, 5, 6, 4, 6, 5, 7, 5, 5, 4, 5, 7, 6, 5, 6, 6, 7, 6, 5, 5, 6,
       5, 7, 5, 6, 6, 5, 7, 5, 5, 5, 6, 7, 7, 5, 5, 6, 6, 7, 6, 5, 6, 6,
       6, 6, 6, 7, 4, 5, 5, 7, 5, 5, 5, 5, 6, 6, 5, 7, 5, 6, 6, 6, 5, 4,
       6, 7, 6, 7, 5, 6, 6, 5, 5, 6, 5, 6, 4, 5, 6, 6, 5, 6, 6, 5, 5, 6,
       7, 7, 6, 5, 6, 6, 5, 6, 5, 6, 5, 5, 5, 6, 6, 6, 7, 5, 5, 6, 5, 7,
       5, 6, 4, 6, 6, 8, 6, 5, 5, 6, 5, 7, 6, 6, 5,

In [47]:
x_test.iloc[0]

fixed acidity            7.7000
volatile acidity         0.5600
citric acid              0.0800
residual sugar           2.5000
chlorides                0.1140
free sulfur dioxide     14.0000
total sulfur dioxide    46.0000
density                  0.9971
pH                       3.2400
sulphates                0.6600
alcohol                  9.6000
Name: 803, dtype: float64

### NOW WE WILL SEE THE ACCURACY

In [58]:
print_score(knn3, x_train, y_train, x_test, y_test, train=True)
print_score(knn3, x_train, y_train, x_test, y_test, train=False)

Train Result:
Accuracy Score: 100.00%
_______________________________________________
CLASSIFICATION REPORT:
             3     4      5      6      7     8  accuracy  macro avg  weighted avg
precision  1.0   1.0    1.0    1.0    1.0   1.0       1.0        1.0           1.0
recall     1.0   1.0    1.0    1.0    1.0   1.0       1.0        1.0           1.0
f1-score   1.0   1.0    1.0    1.0    1.0   1.0       1.0        1.0           1.0
support    9.0  43.0  551.0  506.0  157.0  13.0       1.0     1279.0        1279.0
_______________________________________________
Confusion Matrix: 
 [[  9   0   0   0   0   0]
 [  0  43   0   0   0   0]
 [  0   0 551   0   0   0]
 [  0   0   0 506   0   0]
 [  0   0   0   0 157   0]
 [  0   0   0   0   0  13]]

Test Result:
Accuracy Score: 60.94%
_______________________________________________
CLASSIFICATION REPORT:
             3     4           5           6          7    8  accuracy   macro avg  weighted avg
precision  0.0   0.0    0.627451    0.58

C:\Users\hp\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\hp\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\hp\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
