In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt
from  sklearn.model_selection import train_test_split , GridSearchCV ,GroupKFold
from sklearn.metrics import accuracy_score ,  confusion_matrix ,  precision_score , roc_auc_score , roc_curve
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from pandas_profiling import ProfileReport
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
import pickle

def print_score(clf, X_train, y_train, X_test, y_test, train=True):
    if train:
        pred = clf.predict(X_train)
        clf_report = pd.DataFrame(classification_report(y_train, pred, output_dict=True))
        print("Train Result:\n================================================")
        print(f"Accuracy Score: {accuracy_score(y_train, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{clf_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_train, pred)}\n")
        
    elif train==False:
        pred = clf.predict(X_test)
        clf_report = pd.DataFrame(classification_report(y_test, pred, output_dict=True))
        print("Test Result:\n================================================")        
        print(f"Accuracy Score: {accuracy_score(y_test, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{clf_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_test, pred)}\n")

###  SUPPORT VECTOR CLASSIFIER 

In [2]:
df = pd.read_csv("winequality-red.csv")
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [4]:
x = df.drop(columns=['quality'])
y = df.quality

In [5]:
x_train, x_test, y_train, y_test = train_test_split(x, y , test_size=0.2 , random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_train.shape)

(1279, 11)
(320, 11)
(1279,)
(1279,)


In [21]:
from sklearn.svm import SVC
svc_clf = SVC()
svc_clf.fit(x_train , y_train)


SVC()

In [34]:
y_predict = svc_clf.predict(x_test)   ### THIS IS THE  PREDICTED DATA
y_predict

array([5, 5, 6, 6, 6, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 6, 5, 6, 6,
       6, 6, 6, 6, 6, 5, 5, 6, 5, 5, 6, 6, 6, 5, 6, 6, 6, 6, 6, 5, 6, 5,
       6, 6, 6, 6, 5, 6, 5, 5, 6, 5, 5, 5, 6, 5, 6, 6, 5, 6, 6, 5, 6, 6,
       6, 5, 6, 5, 6, 5, 6, 6, 6, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 5, 6,
       6, 6, 6, 5, 6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5,
       6, 5, 6, 5, 6, 6, 6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6,
       5, 6, 6, 6, 6, 5, 5, 6, 6, 5, 6, 6, 6, 5, 6, 6, 5, 5, 6, 6, 5, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 6, 5, 6, 5, 5, 5, 6, 6, 5, 7, 6,
       6, 5, 5, 5, 6, 6, 5, 6, 6, 5, 6, 6, 6, 5, 6, 5, 6, 6, 5, 6, 5, 5,
       6, 6, 6, 5, 6, 5, 6, 5, 5, 6, 6, 5, 5, 5, 6, 6, 6, 6, 5, 5, 6, 5,
       6, 5, 6, 6, 6, 5, 6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 5,
       5, 6, 6, 5, 6, 5, 6, 5, 5, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 5, 6,
       6, 6, 5, 5, 6, 6, 6, 6, 6, 5, 6, 5, 6, 5, 6, 6, 6, 6, 6, 5, 5, 6,
       5, 5, 6, 6, 5, 6, 6, 6, 5, 6, 5, 6, 6, 6, 6,

In [23]:
np.array(y_test)

array([6, 5, 6, 5, 6, 5, 5, 5, 5, 6, 7, 3, 5, 5, 6, 7, 5, 7, 8, 5, 5, 6,
       5, 6, 6, 6, 7, 6, 5, 6, 5, 5, 6, 5, 6, 5, 7, 5, 4, 6, 5, 5, 7, 5,
       5, 6, 7, 6, 5, 6, 5, 5, 5, 7, 6, 6, 6, 5, 5, 5, 5, 7, 5, 6, 6, 5,
       6, 5, 6, 5, 6, 4, 6, 6, 6, 5, 8, 5, 6, 6, 5, 6, 5, 6, 6, 7, 5, 6,
       7, 4, 7, 6, 5, 5, 5, 6, 5, 6, 5, 6, 5, 5, 5, 7, 6, 7, 6, 5, 6, 5,
       8, 5, 6, 5, 6, 7, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 7, 6, 5, 5, 6, 5,
       5, 5, 6, 5, 5, 5, 5, 6, 7, 6, 8, 5, 5, 5, 6, 6, 6, 5, 6, 7, 6, 5,
       6, 5, 5, 6, 6, 6, 7, 5, 7, 5, 5, 5, 6, 6, 5, 5, 6, 5, 7, 6, 7, 6,
       6, 5, 5, 6, 4, 6, 5, 7, 5, 5, 4, 5, 7, 6, 5, 6, 6, 7, 6, 5, 5, 6,
       5, 7, 5, 6, 6, 5, 7, 5, 5, 5, 6, 7, 7, 5, 5, 6, 6, 7, 6, 5, 6, 6,
       6, 6, 6, 7, 4, 5, 5, 7, 5, 5, 5, 5, 6, 6, 5, 7, 5, 6, 6, 6, 5, 4,
       6, 7, 6, 7, 5, 6, 6, 5, 5, 6, 5, 6, 4, 5, 6, 6, 5, 6, 6, 5, 5, 6,
       7, 7, 6, 5, 6, 6, 5, 6, 5, 6, 5, 5, 5, 6, 6, 6, 7, 5, 5, 6, 5, 7,
       5, 6, 4, 6, 6, 8, 6, 5, 5, 6, 5, 7, 6, 6, 5,

In [32]:
svc_clf.predict([x_test.iloc[0]])

C:\Users\hp\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([5], dtype=int64)

In [25]:
x_test.iloc[0]

fixed acidity            7.7000
volatile acidity         0.5600
citric acid              0.0800
residual sugar           2.5000
chlorides                0.1140
free sulfur dioxide     14.0000
total sulfur dioxide    46.0000
density                  0.9971
pH                       3.2400
sulphates                0.6600
alcohol                  9.6000
Name: 803, dtype: float64

In [26]:
y_test.iloc[0]

6

In [19]:
print("Test SCORE : - " , svc_clf.score(x_test , y_test)*100)    #   test score
print("Train SCORE : - " , svc_clf.score(x_train, y_train)*100)  #   train score

Test SCORE : -  50.9375
Train SCORE : -  51.29007036747459


In [27]:
print_score(svc_clf, x_train, y_train, x_test, y_test, train=True)
print_score(svc_clf, x_train, y_train, x_test, y_test, train=False)

Train Result:
Accuracy Score: 51.29%
_______________________________________________
CLASSIFICATION REPORT:
             3     4           5           6           7     8  accuracy  \
precision  0.0   0.0    0.642857    0.448718    1.000000   0.0  0.512901   
recall     0.0   0.0    0.490018    0.760870    0.006369   0.0  0.512901   
f1-score   0.0   0.0    0.556128    0.564516    0.012658   0.0  0.512901   
support    9.0  43.0  551.000000  506.000000  157.000000  13.0  0.512901   

             macro avg  weighted avg  
precision     0.348596      0.577221  
recall        0.209543      0.512901  
f1-score      0.188884      0.464471  
support    1279.000000   1279.000000  
_______________________________________________
Confusion Matrix: 
 [[  0   0   1   8   0   0]
 [  0   0  12  31   0   0]
 [  0   0 270 281   0   0]
 [  0   0 121 385   0   0]
 [  0   0  15 141   1   0]
 [  0   0   1  12   0   0]]

Test Result:
Accuracy Score: 50.94%
_______________________________________________


C:\Users\hp\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\hp\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\hp\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\h

In [35]:
print(classification_report(y_test , y_predict))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00        10
           5       0.60      0.51      0.55       130
           6       0.46      0.73      0.56       132
           7       1.00      0.02      0.05        42
           8       0.00      0.00      0.00         5

    accuracy                           0.51       320
   macro avg       0.34      0.21      0.19       320
weighted avg       0.56      0.51      0.46       320



C:\Users\hp\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\hp\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\hp\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [36]:
param ={"kernel":['linear', 'poly', 'rbf', 'sigmoid' ],
        'C':[.1,.4 , .6 , 1,2,3,100,200,500],
        'gamma':[.001,.1,.4,.004,.003]
    } 
svm_grid = GridSearchCV(svc , param_grid=param , verbose=3 )
svm_grid.fit(x_train,y_train)

In [37]:
svm_grid.best_params_

In [38]:
svc1 = SVC(kernel='poly')
svc1.fit(x_train,y_train)

In [41]:
svc1.score(x_test,y_test)

### SUPPORT VECTOR REGRESSOR

In [42]:
pwd

'E:\\Jupyter_Project\\jupyter_projects\\INEURON\\DecisionTree'

In [43]:
ls

 Volume in drive E is Local Disk
 Volume Serial Number is 5439-F112

 Directory of E:\Jupyter_Project\jupyter_projects\INEURON\DecisionTree

01-09-2022  00:07    <DIR>          .
01-09-2022  00:07    <DIR>          ..
31-08-2022  23:38    <DIR>          .ipynb_checkpoints
24-08-2022  21:34            16,085 Admission_Prediction.csv
31-08-2022  23:37         1,071,420 BAGGING TECHNIQUES.ipynb
31-08-2022  23:57        11,784,228 Decision_tree.ipynb
29-08-2022  22:47           212,227 dt_model_1.png
31-08-2022  23:35            45,114 K_Nearest_Neighbour.ipynb
31-08-2022  21:53           142,444 knn1.pkl
31-08-2022  22:13           155,763 knn3.pkl
01-09-2022  00:07            28,072 support vector Classifier and  Regressor.ipynb
21-09-2019  19:06           100,951 winequality-red.csv
               9 File(s)     13,556,304 bytes
               3 Dir(s)  442,893,713,408 bytes free


In [59]:
data2 = pd.read_csv("Admission_Prediction.csv")
data2.head(2)

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
0           1      337.0        118.0                4.0  4.5  4.5  9.65   
1           2      324.0        107.0                4.0  4.0  4.5  8.87   

   Research  Chance of Admit  
0         1             0.92  
1         1             0.76

In [60]:
data2.isnull().mean()*100

Serial No.           0.0
GRE Score            3.0
TOEFL Score          2.0
University Rating    3.0
SOP                  0.0
LOR                  0.0
CGPA                 0.0
Research             0.0
Chance of Admit      0.0
dtype: float64

In [61]:
data2.dropna(subset= ['GRE Score' , 'TOEFL Score' , 'University Rating'] , inplace= True)
data2.isnull().mean()*100

Serial No.           0.0
GRE Score            0.0
TOEFL Score          0.0
University Rating    0.0
SOP                  0.0
LOR                  0.0
CGPA                 0.0
Research             0.0
Chance of Admit      0.0
dtype: float64

In [62]:
x = data2.drop(['Serial No.', 'Chance of Admit'] , axis=1)
x

GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  Research
0        337.0        118.0                4.0  4.5  4.5  9.65         1
1        324.0        107.0                4.0  4.0  4.5  8.87         1
3        322.0        110.0                3.0  3.5  2.5  8.67         1
4        314.0        103.0                2.0  2.0  3.0  8.21         0
5        330.0        115.0                5.0  4.5  3.0  9.34         1
..         ...          ...                ...  ...  ...   ...       ...
495      332.0        108.0                5.0  4.5  4.0  9.02         1
496      337.0        117.0                5.0  5.0  5.0  9.87         1
497      330.0        120.0                5.0  4.5  5.0  9.56         1
498      312.0        103.0                4.0  4.0  5.0  8.43         0
499      327.0        113.0                4.0  4.5  4.5  9.04         0

[460 rows x 7 columns]

In [63]:
y = data2['Chance of Admit']
y

0      0.92
1      0.76
3      0.80
4      0.65
5      0.90
       ... 
495    0.87
496    0.96
497    0.93
498    0.73
499    0.84
Name: Chance of Admit, Length: 460, dtype: float64

In [65]:
x_train , x_test , y_train , y_test  = train_test_split(x , y , test_size=0.2 , random_state=42)
print("x_train", x_train.shape)
print("x_test", x_test.shape)
print("y_train", y_train.shape)
print("y_test" , y_test.shape)

x_train (368, 7)
x_test (92, 7)
y_train (368,)
y_test (92,)


In [67]:
from sklearn.svm import SVR
svr = SVR(verbose=True)
svr.fit(x_train , y_train)

[LibSVM]

SVR(verbose=True)

In [71]:
y_predict = svr.predict(x_test)
y_predict               ### THIS IS THE ACTUAL DATA

array([0.80138436, 0.81703614, 0.6666579 , 0.61828617, 0.63497783,
       0.69373942, 0.81248813, 0.61378809, 0.78667003, 0.88061   ,
       0.55914819, 0.87493212, 0.69721627, 0.86992361, 0.69146299,
       0.81638471, 0.71475713, 0.55128009, 0.70362953, 0.87657946,
       0.50835042, 0.78652698, 0.67938911, 0.79242771, 0.7678491 ,
       0.65212742, 0.90316726, 0.55856126, 0.79043804, 0.78758743,
       0.69670816, 0.85185965, 0.57906117, 0.73063997, 0.62181136,
       0.71429245, 0.78165994, 0.51700322, 0.70707922, 0.59574261,
       0.65792275, 0.79205963, 0.70883743, 0.71511862, 0.66336807,
       0.64794623, 0.69392112, 0.84786299, 0.59252431, 0.74559965,
       0.76446111, 0.7831793 , 0.65520427, 0.74404762, 0.62008979,
       0.67419649, 0.53905228, 0.67864071, 0.84149137, 0.65937974,
       0.6675721 , 0.72858133, 0.76202697, 0.72627032, 0.63999179,
       0.81916814, 0.7580034 , 0.66229521, 0.77241531, 0.78918362,
       0.5719265 , 0.5687183 , 0.66831533, 0.77147859, 0.76729

In [72]:
np.array(y_test)    ### THIS IS THE FINAL DATA

array([0.8 , 0.94, 0.74, 0.62, 0.65, 0.72, 0.79, 0.62, 0.76, 0.94, 0.54,
       0.95, 0.64, 0.91, 0.73, 0.93, 0.74, 0.54, 0.73, 0.92, 0.46, 0.89,
       0.67, 0.91, 0.82, 0.75, 0.96, 0.34, 0.84, 0.84, 0.56, 0.93, 0.68,
       0.73, 0.56, 0.74, 0.92, 0.49, 0.66, 0.64, 0.71, 0.91, 0.84, 0.74,
       0.71, 0.67, 0.72, 0.9 , 0.68, 0.92, 0.8 , 0.74, 0.64, 0.87, 0.52,
       0.73, 0.42, 0.58, 0.94, 0.61, 0.66, 0.63, 0.87, 0.65, 0.53, 0.94,
       0.78, 0.73, 0.52, 0.82, 0.42, 0.58, 0.64, 0.85, 0.92, 0.54, 0.96,
       0.61, 0.81, 0.82, 0.72, 0.83, 0.67, 0.84, 0.64, 0.67, 0.76, 0.63,
       0.72, 0.62, 0.82, 0.89])

In [74]:
from sklearn.metrics import    r2_score
r2_score(y_test ,  y_predict)       #TO CHECK THE SCORE OF THE MODELS

0.6832671453160493

In [76]:
## This is also a way to check the score 


# svr.score(x_test,y_test)*100   ## Test score
print("Test SCORE : - " , svr.score(x_test , y_test)*100)    #   test score
print("Train SCORE : - " , svr.score(x_train, y_train)*100)  #   train score

Test SCORE : -  68.32671453160492
Train SCORE : -  65.88530051858054
